# Generated by Django 3.2.7 on 2021-09-11 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200, verbose_name='cname')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('role', models.CharField(max_length=100, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=200, verbose_name='mname')),
                ('language', models.CharField(max_length=200, verbose_name='language')),
                ('poster', models.CharField(max_length=200, verbose_name='poster')),
                ('movie_description', models.CharField(max_length=1000, verbose_name='desc')),
                ('release_date', models.CharField(max_length=200, verbose_name='date')),
                ('status', models.CharField(max_length=200, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='movie_person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=200, verbose_name='pname')),
                ('person_photo', models.CharField(max_length=1000, verbose_name='photo')),
            ],
        ),
        migrations.CreateModel(
            name='production',
            fields=[
                ('production_id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_name', models.CharField(max_length=200, verbose_name='bname')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=200, verbose_name='uname')),
                ('User_email', models.CharField(max_length=100, verbose_name='email')),
                ('User_phone', models.CharField(max_length=100, verbose_name='phone')),
                ('Log_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.login')),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=1000, verbose_name='pname')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.movie')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=100, verbose_name='rating')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.movie')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.production'),
        ),
        migrations.CreateModel(
            name='move_category',
            fields=[
                ('movie_catid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('move', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.movie')),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100, verbose_name='date')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.movie')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
        migrations.CreateModel(
            name='crew',
            fields=[
                ('crew_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_role', models.CharField(max_length=100, verbose_name='prole')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.movie')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.movie_person')),
            ],
        ),
    ]
