# Generated by Django 4.1.7 on 2023-03-26 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('theatreid', models.AutoField(primary_key=True, serialize=False)),
                ('theatre_name', models.CharField(max_length=200)),
                ('theatre_place', models.CharField(max_length=200)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.login')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.AutoField(primary_key=True, serialize=False)),
                ('staffname', models.CharField(max_length=200)),
                ('staffimage', models.ImageField(upload_to='images')),
                ('staffphone', models.BigIntegerField()),
                ('staffemail', models.EmailField(max_length=254)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.login')),
            ],
        ),
    ]
