# Generated by Django 4.1.7 on 2023-03-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_theatre_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='reg_num',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
    ]
