# Generated by Django 4.1.7 on 2023-03-26 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_theatre_reg_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='thtr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.theatre'),
        ),
        migrations.AddField(
            model_name='theatre',
            name='add',
            field=models.CharField(default='0', max_length=300),
            preserve_default=False,
        ),
    ]
