# Generated by Django 4.1.7 on 2023-03-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_add_theatre_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('showid', models.AutoField(primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.movie')),
                ('teatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.theatre')),
            ],
        ),
    ]
