# Generated by Django 4.1.7 on 2023-04-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_show_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='rate',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
