# Generated by Django 4.1.7 on 2023-04-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_show_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='enddate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='show',
            name='startdate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='show',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
