# Generated by Django 4.1.7 on 2023-04-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_show_enddate_show_startdate_show_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='teatre',
            new_name='theatre',
        ),
    ]
