# Generated by Django 4.1.7 on 2023-04-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_teatre_show_theatre'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='seats',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
