# Generated by Django 4.1.7 on 2023-04-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_show_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='enddate',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='show',
            name='startdate',
        ),
    ]
