# Generated by Django 4.1.7 on 2023-04-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_enddate_show_date_remove_show_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
    ]
