# Generated by Django 4.1.7 on 2023-04-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='tickets',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
