# Generated by Django 4.2.1 on 2023-05-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_booking_amount_booking_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='analaysis',
            field=models.CharField(default=0, max_length=100, verbose_name='analysis'),
            preserve_default=False,
        ),
    ]
